name: "PR Analytics"
on:
  workflow_dispatch:

permissions: read-all
  
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Runs script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          LABELS: "Report"
          ASSIGNEES: "user-1, user-2, user-3"
          GITHUB_OWNER_FOR_ISSUE: "owner"
          GITHUB_REPO_FOR_ISSUE: "PR_analytics"
          GITHUB_OWNERS_REPOS: "david-the-droid/PR_analytics"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_PERIOD: "months:3"
          AGGREGATE_VALUE_METHODS: average
          SHOW_STATS_TYPES: timeline
          PERIOD_SPLIT_UNIT: none
          TOP_LIST_AMOUNT: 5
          EXECUTION_OUTCOME: existing-issue
          ISSUE_NUMBER: 1
